development:
  secret_key_base: XXXXXXXXXXXXXXXXX
  google_client_id: 554630340188-4c8rierfur1bi8ebigfgddt34pf2qqmc.apps.googleusercontent.com
  google_client_secret: 8tNZl69L3T47QjLsduRVDQLG
  facebook_client_id: 349075529278264
  facebook_client_secret: 0af133202fd4754ac0714588778d4081
